[versions]
compileSdk = "35"
minSdk = "24"
targetSdk = "35"

androidx-appcompat = "1.7.0"
android-gradle-plugin = "8.8.0"
androidx-activity-compose = "1.10.0"
androidx-compose-bom = "2025.01.00"
androidx-lifecycle-compose = "2.8.4"
androidx-compose-navigation = "2.8.5"
androidx-compose-ripple = "1.7.6"
androidx-core-splashscreen = "1.0.1"
androidx-corektx = "1.15.0"

compose-multiplatform = "1.7.3"
androidx-compose-preview = "1.7.6"

kotlin = "2.1.0"
kotlin-serialization-json = "1.8.0"
nomanr-composables = "0.0.1-alpha.12"
spotless = "6.25.0"
vanniktech-maven-publish = "0.30.0"
material-navigation = "1.7.0-beta02"

ksp = "2.1.0-1.0.29"


[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-compose-navigation" }
androidx-compose-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "androidx-compose-ripple" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

androidx-lifecycle-runtime-multiplatform = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-compose" }
androidx-corektx = { module = "androidx.core:core-ktx", version.ref = "androidx-corektx" }

androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-preview" }

kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }

nomanr-composables = { group = "com.nomanr", name = "composables", version.ref = "nomanr-composables" }

androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.8.0-alpha11"}
material-navigation = { module = "org.jetbrains.compose.material:material-navigation", version.ref = "material-navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }





